- clean: ['~', '~/.config']

- link:
   ~/.suit: ''
   ~/.zshrc: 'zsh/zshrc'
   ~/.gitconfig: 'git/gitconfig'
   ~/.gitignore_global: 'git/gitignore_global'
   ~/.atom: 'atom'

- shell:
  - git submodule update --init --recursive
  - ~/.suit/bootstrap/init.sh
