SUIT_ZSH_HOME=~/.suit/zsh

source $SUIT_ZSH_HOME/checks.zsh
source $SUIT_ZSH_HOME/exports.zsh

source $SUIT_ZSH_HOME/settings.zsh
source $SUIT_ZSH_HOME/aliases.zsh
source $SUIT_ZSH_HOME/completion.zsh

source $SUIT_ZSH_HOME/theme/pure/pure.zsh
source $SUIT_ZSH_HOME/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

[[ -r ~/.zshrc_local ]] && source ~/.zshrc_local
